"""
BrailleVision â€” Dataset Merger & Splitter

Merges all downloaded raw datasets into a single YOLO-format dataset
with 70% train / 20% val / 10% test split.

Usage:
    python training/scripts/merge_and_split.py
    python training/scripts/merge_and_split.py --raw dataset/raw --out dataset
"""

import argparse
import hashlib
import random
import shutil
from pathlib import Path

ROOT = Path(__file__).parent.parent.parent
DEFAULT_RAW = ROOT / "dataset" / "raw"
DEFAULT_OUT = ROOT / "dataset"

TRAIN_RATIO = 0.70
VAL_RATIO = 0.20
TEST_RATIO = 0.10


def file_hash(path: Path) -> str:
    """MD5 hash of file content for deduplication."""
    h = hashlib.md5()
    with open(path, "rb") as f:
        h.update(f.read(65536))
    return h.hexdigest()


def collect_pairs(raw_dir: Path):
    """
    Recursively scan raw_dir for (image, label) pairs.
    Both files must exist and the label must be non-empty.
    Returns list of (img_path, lbl_path).
    """
    image_exts = {".jpg", ".jpeg", ".png"}
    pairs = []
    seen_hashes = set()

    for img_path in sorted(raw_dir.rglob("*")):
        if img_path.suffix.lower() not in image_exts:
            continue

        # Find matching label
        lbl_path = img_path.with_suffix(".txt")
        if not lbl_path.exists():
            # Try labels/ sibling directory
            lbl_path = img_path.parent.parent / "labels" / (img_path.stem + ".txt")
        if not lbl_path.exists():
            # Try dataset-level labels sibling
            lbl_path = img_path.parent.parent.parent / "labels" / img_path.parent.name / (img_path.stem + ".txt")
        if not lbl_path.exists() or lbl_path.stat().st_size == 0:
            continue

        # Deduplicate by image hash
        h = file_hash(img_path)
        if h in seen_hashes:
            continue
        seen_hashes.add(h)

        pairs.append((img_path, lbl_path))

    return pairs


def split_pairs(pairs, seed=42):
    """Randomly split into train/val/test."""
    random.seed(seed)
    shuffled = list(pairs)
    random.shuffle(shuffled)

    n = len(shuffled)
    n_train = int(n * TRAIN_RATIO)
    n_val = int(n * VAL_RATIO)

    train = shuffled[:n_train]
    val = shuffled[n_train:n_train + n_val]
    test = shuffled[n_train + n_val:]

    return train, val, test


def copy_split(pairs, out_dir: Path, split_name: str) -> int:
    """Copy image-label pairs into train/val/test directories."""
    img_dir = out_dir / "images" / split_name
    lbl_dir = out_dir / "labels" / split_name
    img_dir.mkdir(parents=True, exist_ok=True)
    lbl_dir.mkdir(parents=True, exist_ok=True)

    for i, (img_path, lbl_path) in enumerate(pairs):
        stem = f"{split_name}_{i:06d}"
        shutil.copy2(img_path, img_dir / (stem + img_path.suffix.lower()))
        shutil.copy2(lbl_path, lbl_dir / (stem + ".txt"))

    return len(pairs)


def write_data_yaml(out_dir: Path):
    """Write the YOLO data.yaml configuration file."""
    yaml_content = f"""# BrailleVision â€” YOLO Dataset Configuration
# Generated by merge_and_split.py

path: {out_dir.resolve()}
train: images/train
val: images/val
test: images/test

nc: 1
names:
  - dot
"""
    (out_dir / "data.yaml").write_text(yaml_content)
    print(f"  âœ“ data.yaml written")


def main():
    parser = argparse.ArgumentParser(description="Merge and split Braille datasets")
    parser.add_argument("--raw", default=str(DEFAULT_RAW), help="Raw datasets directory")
    parser.add_argument("--out", default=str(DEFAULT_OUT), help="Output YOLO dataset directory")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    args = parser.parse_args()

    raw_dir = Path(args.raw)
    out_dir = Path(args.out)

    if not raw_dir.exists():
        print(f"Error: Raw dataset directory not found: {raw_dir}")
        print("Run download_datasets.py and generate_synthetic.py first.")
        return

    print("=" * 55)
    print(" BrailleVision Dataset Merger")
    print("=" * 55)
    print(f" Raw source: {raw_dir}")
    print(f" Output:     {out_dir}\n")

    print("Collecting image-label pairs...")
    pairs = collect_pairs(raw_dir)
    print(f"  Found {len(pairs)} valid annotated pairs")

    if len(pairs) == 0:
        print("No annotated pairs found. Run download_datasets.py first.")
        return

    train, val, test = split_pairs(pairs, seed=args.seed)

    print(f"  Split: {len(train)} train / {len(val)} val / {len(test)} test")
    print("\nCopying files...")

    n_train = copy_split(train, out_dir, "train")
    n_val = copy_split(val, out_dir, "val")
    n_test = copy_split(test, out_dir, "test")

    write_data_yaml(out_dir)

    print("\n" + "=" * 55)
    print(" MERGE COMPLETE")
    print("=" * 55)
    print(f" Train: {n_train} images")
    print(f" Val:   {n_val} images")
    print(f" Test:  {n_test} images")
    print(f" Total: {n_train + n_val + n_test} images")
    print(f" data.yaml: {out_dir / 'data.yaml'}")
    print("\nNext step: python training/scripts/verify_dataset.py")


if __name__ == "__main__":
    main()
